memcached:
  image: memcached
  ports:
    - "11211"
webpackdevserver:
  build: .
  command: webpack-dev-server --config webpack/webpack.hot.config.js --hot --progress --inline --port 2998
  volumes:
      - .:/app
  ports:
    - "2998:2998"
app:
  build: .
  command: bundle exec rails s -p 2999 -b '0.0.0.0'
  volumes:
    - .:/app
  env_file: .env
  ports:
    - "2999:2999"
  links:
    - memcached
    - webpackdevserver